export const DEFAULT_STRING_LENGTH_LIMIT = 50;
export const PHONE_LENGTH_LIMIT = 15;
export const DESCRIPTION_LENGTH_LIMIT = 300;
export enum TIME_SLOT_TYPES {
  RECURRING = 'RECURRING',
  SINGLE = 'SINGLE',
}
export enum COMMUTE_METHOD_TYPES {
  WALK = 'WALK',
  BIKE = 'BIKE',
  TAXI = 'TAXI',
  BUS = 'BUS',
  CAR = 'CAR',
}
